name: Deployment

on: 
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
       
      - name: Set Envars
        run: |
          export TF_VAR_aws_access_key="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export TF_VAR_aws_secret_access_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export TF_VAR_aws_region="us-east-1"
               
      - name: Initialize Terraform
        run: terraform init
        working-directory: . # Set this to the directory where your Terraform files are located

      - name: Validate Terraform
        run: terraform validate
        working-directory: . 

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: . # Set this to the directory where your Terraform files are located
      
      - name: Output API URL
        run: |
          terraform output