name: Deployment

on: 
  push:
    branches: [ main ]

permissions:
  contents: read 
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
       
      - name: Set Envars
        run: |
          echo "TF_VAR_aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_region=us-east-1" >> $GITHUB_ENV
               
      - name: Set Terraform Debug Log
        run: echo "TF_LOG=DEBUG" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init
        working-directory: . 

      - name: Validate Terraform
        run: terraform validate
        working-directory: . 

      - name: Debug environment variables
        run: |
          echo "AWS_ACCESS_KEY_ID is set: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}"
          echo "AWS_SECRET_ACCESS_KEY is set: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"
          echo "AWS_REGION is set: ${{ secrets.AWS_REGION != '' }}"

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: . 

      - name: Output API URL
        run: |
          terraform output api_gateway_endpoint
