name: Deployment

on: 
  push:
    branches: [ main ]

jobs:
  aws:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
    
  terraform:
    runs-on: ubuntu-latest
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
               
      - name: Initialize Terraform
        run: terraform init
        working-directory: . # Set this to the directory where your Terraform files are located

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: . # Set this to the directory where your Terraform files are located
      
      - name: Output API URL
        run: |
          terraform output